Transformer

In [17]:

import numpy as np
from typing import List
import pickle
%reload_ext autoreload
%autoreload 2
from new_unit import Data, get_config, cross_validate, f1_acc
from models import GCN, MPNN, CNN, Transformer

from const import Descriptors
from sklearn.metrics import f1_score, confusion_matrix, roc_curve,precision_recall_curve, auc
from unit import compute_metrics, squeeze_if_needed,transformer_predict,cnn_predict


import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
np.random.seed(42)

In [ ]:
Model = "Transformer"
model_path = "./FEAOF/trained_models/DL/Transformer.pkl"
config_path = "./configures/optimized/train_split/Transformer_TOKENS.yml"

file_name = f"./trained_models/DL/{Model}.csv"

with open(file_name,"w") as p:
    p.write("auc_score, pr_auc, AC, f1, SN, PR, SP, CCR, MCC\n")

In [ ]:

with open(model_path, 'rb') as handle:
    model_project = pickle.load(handle)

hyperparameters = get_config(config_path)
hyperparameters = {k: v.item() if isinstance(v, np.generic) else v for k, v in hyperparameters.items()}
model = Transformer(None, 32, **hyperparameters).model

model.load_state_dict(model_project.model)

In [20]:
model.eval()
data = Data("./data/processed/Train_Val.csv")
data(Descriptors.TOKENS)
y_hat = transformer_predict(model,data.x_test,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Train_Val.csv
data number :  (10543, 4)
Binary classification performace metrics:
[[561 109]
 [150 297]]
TP, FN, TN, FP
297, 150, 561, 109


(0.8463, 0.7876, 0.7681, 0.6964, 0.6644, 0.7315, 0.8373, 0.7509, 0.5111)

In [21]:
model.eval() # close dropout of moldes
data = Data("./data/processed/Test_1.csv")
data(Descriptors.TOKENS)

y_hat = transformer_predict(model,data.x_test,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Test_1.csv
data number :  (177, 4)
Binary classification performace metrics:
[[108  21]
 [ 23  25]]
TP, FN, TN, FP
25, 23, 108, 21


(0.7602, 0.4687, 0.7514, 0.5319, 0.5208, 0.5435, 0.8372, 0.679, 0.3629)

In [22]:
model.eval() # close dropout of moldes
data = Data("./data/processed/Test_2.csv")
data(Descriptors.TOKENS)

y_hat = transformer_predict(model,data.x_test,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Test_2.csv
data number :  (379, 4)
Binary classification performace metrics:
[[228  47]
 [ 40  64]]
TP, FN, TN, FP
64, 40, 228, 47


(0.8033, 0.5681, 0.7704, 0.5953, 0.6154, 0.5766, 0.8291, 0.7222, 0.4358)

CNN

In [47]:

import numpy as np
from typing import List
import pickle
%reload_ext autoreload
%autoreload 2
from new_unit import Data, get_config, cross_validate, f1_acc
from models import GCN, MPNN, CNN, Transformer

from const import Descriptors
from sklearn.metrics import f1_score, confusion_matrix, roc_curve,precision_recall_curve, auc
from unit import compute_metrics, squeeze_if_needed,transformer_predict,cnn_predict


import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [ ]:
Model = "CNN"
model_path = "./FEAOF/trained_models/DL/CNN.pkl"
config_path = "./configures/optimized/train_split/CNN_SMILES.yml"

file_name = f"./trained_models/DL/{Model}.csv"

with open(file_name,"w") as p:
    p.write("auc_score, pr_auc, AC, f1, SN, PR, SP, CCR, MCC\n")

In [49]:
batch_size=32
herg_em=None
with open(model_path, 'rb') as handle:
    model_project = pickle.load(handle)

hyperparameters = get_config(config_path)
hyperparameters = {k: v.item() if isinstance(v, np.generic) else v for k, v in hyperparameters.items()}
model = CNN(herg_em, batch_size, **hyperparameters).model

model.load_state_dict(model_project.model)

<All keys matched successfully>

In [50]:
data = Data("./data/processed/Train_Val.csv")
data(Descriptors.SMILES)
y_hat = cnn_predict(model,data.x_test,batch_size,herg_em,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Train_Val.csv
data number :  (10543, 4)
Binary classification performace metrics:
[[539 131]
 [151 296]]
TP, FN, TN, FP
296, 151, 539, 131


(0.785, 0.7115, 0.7475, 0.6773, 0.6622, 0.6932, 0.8045, 0.7333, 0.4705)

In [51]:
data = Data("./data/processed/Test_1.csv")
data(Descriptors.SMILES)
y_hat = cnn_predict(model,data.x_test,batch_size,herg_em,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Test_1.csv
data number :  (177, 4)
Binary classification performace metrics:
[[87 42]
 [18 30]]
TP, FN, TN, FP
30, 18, 87, 42


(0.6684, 0.4321, 0.661, 0.5, 0.625, 0.4167, 0.6744, 0.6497, 0.271)

In [52]:
data = Data("./data/processed/Test_2.csv")
data(Descriptors.SMILES)
y_hat = cnn_predict(model,data.x_test,batch_size,herg_em,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Test_2.csv
data number :  (379, 4)
Binary classification performace metrics:
[[186  89]
 [ 34  70]]
TP, FN, TN, FP
70, 34, 186, 89


(0.7099, 0.4714, 0.6755, 0.5323, 0.6731, 0.4403, 0.6764, 0.6747, 0.316)

GCN

In [22]:
### MPNN model not trained by Train_DL.py
### Trained by MPNN in FEAOF.py with GRAPH only
import numpy as np
from typing import List
import pickle
%reload_ext autoreload
%autoreload 2
from new_unit import Data, get_config, cross_validate, f1_acc
from models import GCN, MPNN, CNN, Transformer

from const import Descriptors
from sklearn.metrics import f1_score, confusion_matrix, roc_curve,precision_recall_curve, auc
from unit import compute_metrics, squeeze_if_needed,transformer_predict,cnn_predict,gcn_predict
from torch_geometric.loader import DataLoader

import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
batch_size=32
herg_em=None

In [ ]:
Model = "GCN_V2"
model_path = "./trained_models/DL/GCN_GRAPH.pkl" 
config_path = "./configures/optimized/train_split/GCN_GRAPH.yml"

file_name = f"./trained_models/DL/{Model}.csv"

with open(file_name,"w") as p:
    p.write("auc_score, pr_auc, AC, f1, SN, PR, SP, CCR, MCC\n")

In [ ]:

with open(model_path, 'rb') as handle:
    model_para = pickle.load(handle)
hyperparameters = get_config(config_path)
hyperparameters = {k: v.item() if isinstance(v, np.generic) else v for k, v in hyperparameters.items()}
model = GCN(herg_em,batch_size,**hyperparameters).model 

model.load_state_dict(model_para)


In [ ]:
data = Data("./data/processed/Train_Val.csv")
data(Descriptors.GRAPH)
y_hat = gcn_predict(model,data.x_test,herg_em,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

In [29]:
data = Data("./data/processed/Test_1.csv")
data(Descriptors.GRAPH)
y_hat = gcn_predict(model,data.x_test,herg_em,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Test_1.csv
data number :  (177, 4)
Binary classification performace metrics:
[[90 39]
 [15 33]]
TP, FN, TN, FP
33, 15, 90, 39


(0.744, 0.4799, 0.6949, 0.55, 0.6875, 0.4583, 0.6977, 0.6926, 0.3486)

In [30]:
data = Data("./data/processed/Test_2.csv")
data(Descriptors.GRAPH)
y_hat = gcn_predict(model,data.x_test,herg_em,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Test_2.csv
data number :  (379, 4)
Binary classification performace metrics:
[[188  87]
 [ 30  74]]
TP, FN, TN, FP
74, 30, 188, 87


(0.7698, 0.5403, 0.6913, 0.5585, 0.7115, 0.4596, 0.6836, 0.6976, 0.3567)

MPNN

In [23]:
### MPNN model not trained by Train_DL.py
### Trained by MPNN in FEAOF.py with GRAPH only
import numpy as np
from typing import List
import pickle
%reload_ext autoreload
%autoreload 2
from new_unit import Data, get_config, cross_validate, f1_acc
from models import GCN, MPNN, CNN, Transformer

from const import Descriptors
from sklearn.metrics import f1_score, confusion_matrix, roc_curve,precision_recall_curve, auc
from unit import compute_metrics, squeeze_if_needed,transformer_predict,cnn_predict,gcn_predict
from torch_geometric.loader import DataLoader

import torch
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
batch_size=32
herg_em=None

In [ ]:
Model = "MPNN"
model_path = "./trained_models/DL/MPNN_GRAPH.pkl"
config_path = "./configures/optimized/train_split/MPNN_GRAPH.yml"

file_name = f"./trained_models/DL/{Model}.csv"

with open(file_name,"w") as p:
    p.write("auc_score, pr_auc, AC, f1, SN, PR, SP, CCR, MCC\n")

In [ ]:

with open(model_path, 'rb') as handle:
    model_para = pickle.load(handle)
hyperparameters = get_config(config_path)
hyperparameters = {k: v.item() if isinstance(v, np.generic) else v for k, v in hyperparameters.items()}
model = MPNN(herg_em,batch_size,**hyperparameters).model

model.load_state_dict(model_para)


In [ ]:
data = Data("./data/processed/Train_Val.csv")
data(Descriptors.GRAPH)
y_hat = gcn_predict(model,data.x_test,herg_em,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Train_Val.csv
data number :  (10543, 4)
Binary classification performace metrics:
[[580  90]
 [106 341]]
TP, FN, TN, FP
341, 106, 580, 90


(0.8809, 0.8241, 0.8245, 0.7768, 0.7629, 0.7912, 0.8657, 0.8143, 0.6326)

In [ ]:
data = Data("./data/processed/Test_1.csv")
data(Descriptors.GRAPH)
y_hat = gcn_predict(model,data.x_test,herg_em,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Test_1.csv
data number :  (177, 4)
Binary classification performace metrics:
[[106  23]
 [ 21  27]]
TP, FN, TN, FP
27, 21, 106, 23


(0.8014, 0.5185, 0.7514, 0.551, 0.5625, 0.54, 0.8217, 0.6921, 0.3794)

In [ ]:
data = Data("./data/processed/Test_2.csv")
data(Descriptors.GRAPH)
y_hat = gcn_predict(model,data.x_test,herg_em,device)
compute_metrics(np.array(data.y_test),y_hat,file_name)

./data/processed/Test_2.csv
data number :  (379, 4)
Binary classification performace metrics:
[[224  51]
 [ 33  71]]
TP, FN, TN, FP
71, 33, 224, 51


(0.8462, 0.6517, 0.7784, 0.6283, 0.6827, 0.582, 0.8145, 0.7486, 0.4749)